In [2]:
print("hello world!")

hello world!


In [4]:
type(42)

int

In [7]:
type(True)

bool

In [9]:
abs(-4)

4

In [16]:
2/3

0.6666666666666666

In [18]:
int(3.99)

3

In [21]:
float(7)


7.0

In [23]:
2.15

2.15

In [25]:
type(int)

type

In [27]:
print(type(round(2/3)))

<class 'int'>


In [29]:
help

Type help() for interactive help, or help(object) for help about object.

In [33]:
help (round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [37]:
round(2/3, ndigits = 4)

0.6667

In [50]:
def round(num):
    return num + 1

In [53]:
round(3)

4

In [1]:
def c_to_f(degrees_c):
    degrees_f = (9/5) * degrees_c +32
    return degrees_f

In [2]:
c_to_f(100)

212.0

In [3]:
c_to_f(-11)


12.2

In [4]:
freesing_f = c_to_f(0)

In [6]:
freesing_f

32.0

In [8]:
def divide(dividend, divisor):
    output = dividend /divisor
    return output


In [11]:
divide(0, 2)

0.0

In [14]:
divide(2, 0)

ZeroDivisionError: division by zero

In [25]:
def calc_sales_tax(price, tax_rate=0.13):
    tax_amt = price * tax_rate
    return tax_amt

In [27]:
calc_sales_tax(5)

0.65

In [30]:
def cal_total_bill(price, tax_rate=0.13, tip_rate=0.15):
    tax_amt = price * tax_rate
    tip_amt = price * tip_rate
    total_price = price + tax_amt + tip_amt
    return total_price

In [32]:
cal_total_bill(100)

128.0

In [35]:
cal_total_bill(100, 0.18)

133.0

In [37]:
cal_total_bill(100, tip_rate = 0.18)

131.0

In [38]:
def c_to_f(degrees_c):
    '''Convert degrees from Celsius to Fahrenheit'''
    degrees_f = (9/5) * degrees_c +32
    return degrees_f

In [40]:
# String is Python's text data type
# Sequences of characters, including digits and symbols
# surrounded by quotation makrs (iether single or double)

In [42]:
'This is a string'

'This is a string'

In [43]:
"This is also a string"

'This is also a string'

In [44]:
"These quotes do not match'

SyntaxError: EOL while scanning string literal (844737843.py, line 1)

In [45]:
print('And\tor')

And	or


In [46]:
print("Today is April \r30th")

30thy is April 


'hello' + 'world'

In [50]:
'hello' + ' ' + 'world'

'hello world'

In [52]:
'ha' * 3

'hahaha'

In [58]:
'The year is' + ' ' + '2025'

'The year is 2025'

In [59]:
3 == 3

True

In [ ]:
'apple' == 'apple''

True

In [62]:
'Apple' == "aple"

False

In [64]:
'20' == 20

False

In [73]:
first_name = "Ada"
last_name =  "Lovelace"

In [71]:
first_name[2]

'a'

In [76]:
last_name[4]

'l'

In [80]:
last_name[4:6]

'la'

In [82]:
last_name[:5]

'Lovel'

In [84]:
last_name[2:]

'velace'

In [87]:
print(last_name[1], last_name[5])

o a


In [89]:
print(1, 'fish', 2, 'fish')

1 fish 2 fish


In [93]:
len('this is a loooooooong')

21

In [95]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [98]:
'I am not yelling'.upper()

'I AM NOT YELLING'

In [101]:
'This string is unsuall'.count('e')

0

In [103]:
'file_name.csv'.endswith('.csv')

True

In [106]:
'file name with spaces.scv'.replace(' ', '_') 

'file_name_with_spaces.scv'

In [108]:
fruit = 'banana'

sorted(fruit)

['a', 'a', 'a', 'b', 'n', 'n']

In [110]:
fruit = 'Aa'

sorted(fruit)

['A', 'a']

In [114]:
first_name = 'Ada'
last_name = "Lovelace"

'Ada Lovelace\'s initials are {}. {}.'.format(first_name[0], last_name[0])

"Ada Lovelace's initials are A. L."

In [ ]:
'My favorite seasons are {} and {}'.format('spring', 'winter')

'My favorite seasons are spring and winter'

In [129]:
first_name

'Ada'

In [131]:
f'Ada Lovelace \'s initial is {first_name[0]}'

"Ada Lovelace 's initial is A"

In [124]:
fruit = 'banana'
vegentable = 'beans'

"My favorite fruit and veg are {} and {}, respetively.".format(fruit, vegentable)

'My favorite fruit and veg are banana and beans, respetively.'

In [135]:
season = 'summer'
f'My favorite seasons is {season}'

'My favorite seasons is summer'

In [ ]:
# string to integer

# int() function only convert strings that represent whole numbers into integers.
int('17')

17

In [140]:
int('178.4')

ValueError: invalid literal for int() with base 10: '178.4'

In [142]:
#string to float

float('892')


892.0

In [145]:
#float and int into string

str(37.5)


'37.5'

In [147]:
str(20)


'20'

In [149]:
'20' +str(37.5)

'2037.5'

In [152]:
(7 == 7.0) and (32> 9)

True

In [155]:
is_summer =  True
is_sunny = True
is_summer and is_sunny

True

In [156]:
is_winter = "True" # string with the value "True"
is_cloudy = True # boolean with the value true
is_winter and is_cloudy

True

In [159]:
is_cloudy and is_winter

'True'

In [161]:
"Python" and "python"

'python'

In [163]:
False and "non-empty string"

False

In [165]:
'Python' == 'python' or True

True

In [167]:
'Python' == 'python'

False

In [170]:
not (7 % 2 == 1) or False

False

In [174]:
is_winter = "True"
is_cloudy = True

is_winter or is_cloudy

'True'

In [177]:
year = 2022

if year >= 2000:
    print('We are in the 21st centry.')

We are in the 21st centry.


In [179]:
year = 1999
if year >= 2000:
    print('We are in the 21st century.')
else:
    print('We are not in the 21st centry.')

We are not in the 21st centry.


In [187]:
year = 2025

if year >= 2000:
    print('We are in the 21st century.')
elif year >= 1900:
    print('We are in the 20th centry.')
elif year >= 1800:
    print('We are in the 19st centry.')
else:
    print('We have gone way back in time')

We are in the 21st century.


In [193]:
day_of_week = "Saturday"

if day_of_week == 'Saturday' or day_of_week == 'Sunday':
    print('Weekend')
else: 
    print('Weekday')

Weekend


In [221]:
def eye_exam_covered(age, qualifying_condition, time_since_last_exam):
    '''qualifying_condition is True/False on whether you have an eligible medical condition'''
    if age <= 19:
        if time_since_last_exam >= 12:
            return "you are eligible for 1 major eye exam and any minor assessments."
        else:
            return "it hasn't been 12 months since your last major eye exam."
    elif 20 <= age <= 64:
        if qualifying_condition:
            if time_since_last_exam >= 12:
                return "you are eligible for 1 major eye exam & 2 follow-up minor assessments"
            else:
                return "it hasn't been 12 months since your last major eye exam"
        else:
            return "you do not have an eligible medical condition"
    elif age <= 65:
        if time_since_last_exam >= 18:
            return "you are eligible for 1 major eye exam and 2 follow-up minor assessments"
        else:
            return "it hasn't been 18 months since your last major eye exam"
    else:
        return "invalid age input"

In [223]:
def eye_exam_covered(age, qualifying_condition, time_since_last_exam):
    '''qualifying_condition is True/False on whether you have an eligible medical condition'''
    if age <= 19:
        if time_since_last_exam >= 12:
            return "you are eligible for 1 major eye exam and any minor assessments."
        else:
            return "it hasn't been 12 months since your last major eye exam."
    elif 20 <= age <= 64:
        if qualifying_condition:
            if time_since_last_exam >= 12:
                return "you are eligible for 1 major eye exam & 2 follow-up minor assessments"
            else:
                return "it hasn't been 12 months since your last major eye exam"
        else:
            return "you do not have an eligible medical condition"
    elif age <= 65:
        if time_since_last_exam >= 18:
            return "you are eligible for 1 major eye exam and 2 follow-up minor assessments"
        else:
            return "it hasn't been 18 months since your last major eye exam"
    else:
        return "invalid age input"

In [224]:
eye_exam_covered(27, True, 15)

'you are eligible for 1 major eye exam & 2 follow-up minor assessments'

In [226]:
eye_exam_covered(20, False, 11)

'you do not have an eligible medical condition'

In [231]:
vowels = ['a', 'e', 'i', 'o', 'u']
vowels

['a', 'e', 'i', 'o', 'u']

In [233]:
emply_list = []
type(emply_list)

list

In [235]:
emply_list2 = list()

In [237]:
scores = [90, 80, 70, 70]
grades = ['K', 1, 2, 3, 4, 5]
summary_functions = [len, sum, max, min]

In [240]:
mystery_solvers = [
    ['Sherlock', 'Watson'],
    ['Scooby', 'Shaggy', 'Fred'],
    'Nancy'
]

In [244]:
grades [0]

'K'

In [247]:
grades [1:5]

[1, 2, 3, 4]

In [250]:
grades [-4:]

[2, 3, 4, 5]

In [252]:
grades [1:6]

[1, 2, 3, 4, 5]

In [254]:
grades [10]

IndexError: list index out of range

In [256]:
'Hiro' in 'James loves coffee'

False

In [258]:
vowels

['a', 'e', 'i', 'o', 'u']

In [262]:
'K' in vowels

False

In [264]:
mystery_solvers

[['Sherlock', 'Watson'], ['Scooby', 'Shaggy', 'Fred'], 'Nancy']

In [266]:
mystery_solvers[0]

['Sherlock', 'Watson']

In [269]:
mystery_solvers[0][0]

'Sherlock'

In [272]:
vowels.index('e')

1

In [275]:
perfect_squares = [ 1, 4, 9, 16, 25, 37, 49]
perfect_squares

[1, 4, 9, 16, 25, 37, 49]

In [277]:
julia = 'cheese sandwich'
Hiro = julia


In [279]:
julia

'cheese sandwich'

In [281]:
Hiro

'cheese sandwich'

In [283]:
julia = 'ham sandwich'

In [285]:
julia

'ham sandwich'

In [287]:
Hiro

'cheese sandwich'

In [289]:
julia_list = ['bread', 'cheese', 'bread']

In [291]:
Hiro_list = julia_list

In [293]:
julia_list

['bread', 'cheese', 'bread']

In [295]:
Hiro_list

['bread', 'cheese', 'bread']

In [297]:
julia_list[1] = 'ham'

In [299]:
julia_list

['bread', 'ham', 'bread']

In [301]:
Hiro_list

['bread', 'ham', 'bread']

In [303]:
a = 1
b = a 

In [305]:
a

1

In [306]:
b

1

In [308]:
a = 2

In [310]:
a


2

In [318]:
a = [1,2]

In [319]:
a

[1, 2]

In [320]:
a = b

In [322]:
b 

1

In [324]:
combo = ['burger', 'fries', 'drink']
kid_meal = list(combo)

In [325]:
kid_meal

['burger', 'fries', 'drink']

In [327]:

combo[0] = 'veggie burger'

In [329]:
combo

['veggie burger', 'fries', 'drink']

In [331]:
kid_meal

['burger', 'fries', 'drink']

In [332]:
perfect_squares

[1, 4, 9, 16, 25, 37, 49]

In [334]:
len(perfect_squares)

7

In [336]:
max(perfect_squares)

49

In [338]:
sum(perfect_squares)

141

In [341]:
letters = ['a', 'b', 'c']
numbers = [1, 2, 3]
characters = letters + numbers

In [343]:
characters

['a', 'b', 'c', 1, 2, 3]

In [344]:
letters * 2

['a', 'b', 'c', 'a', 'b', 'c']

In [346]:
numbers * 2

[1, 2, 3, 1, 2, 3]

In [348]:
perfect_squares * 2

[1, 4, 9, 16, 25, 37, 49, 1, 4, 9, 16, 25, 37, 49]

In [350]:
rainbow = ['red', 'orange', 'yellow', 'green', 'blue', 'violet']

In [352]:
#append will add a single element to the end of a list.

rainbow.append('purple')
rainbow

['red', 'orange', 'yellow', 'green', 'blue', 'violet', 'purple', 'purple']

In [356]:
rainbow.append(['purple'])
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'violet',
 'purple',
 'purple',
 ['purple'],
 ['purple']]

In [358]:
# extend used to add elements from an interable to the end of a list
#this will unpack the elements of an iterable and add them on by one to the end of the original list.

rainbow.append(['magenta', 'pink'])
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'violet',
 'purple',
 'purple',
 ['purple'],
 ['purple'],
 ['magenta', 'pink'],
 ['magenta', 'pink']]

In [361]:
rainbow.extend(['magenta', 'pink'])
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'violet',
 'purple',
 'purple',
 ['purple'],
 ['purple'],
 ['magenta', 'pink'],
 ['magenta', 'pink'],
 'magenta',
 'pink',
 'magenta',
 'pink']

In [363]:
rainbow.extend('pale pink')
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'violet',
 'purple',
 'purple',
 ['purple'],
 ['purple'],
 ['magenta', 'pink'],
 ['magenta', 'pink'],
 'magenta',
 'pink',
 'magenta',
 'pink',
 'p',
 'a',
 'l',
 'e',
 ' ',
 'p',
 'i',
 'n',
 'k',
 'p',
 'a',
 'l',
 'e',
 ' ',
 'p',
 'i',
 'n',
 'k']

In [365]:
rainbow.insert(6, 'indigo')

In [367]:
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'violet',
 'indigo',
 'purple',
 'purple',
 ['purple'],
 ['purple'],
 ['magenta', 'pink'],
 ['magenta', 'pink'],
 'magenta',
 'pink',
 'magenta',
 'pink',
 'p',
 'a',
 'l',
 'e',
 ' ',
 'p',
 'i',
 'n',
 'k',
 'p',
 'a',
 'l',
 'e',
 ' ',
 'p',
 'i',
 'n',
 'k']

In [369]:
rainbow.remove('p')

In [371]:
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'violet',
 'indigo',
 'purple',
 'purple',
 ['purple'],
 ['purple'],
 ['magenta', 'pink'],
 ['magenta', 'pink'],
 'magenta',
 'pink',
 'magenta',
 'pink',
 'a',
 'l',
 'e',
 ' ',
 'i',
 'n',
 'k',
 'p',
 'a',
 'l',
 'e',
 ' ',
 'p',
 'i',
 'n',
 'k']

In [372]:
del rainbow[-13:]

In [374]:
rainbow.clear()

In [ ]:
rainbow

[]

In [377]:
rainbow

[]

In [ ]:
# sort () method
fruits = ['pineapple', 'apple', 'kiwi', 'banana']
print(fruits.sort())

None


In [ ]:
print(fruits) # method sorts/modifies the original list in place

['apple', 'banana', 'kiwi', 'pineapple']


In [ ]:
# sort () function

veggies = ['potatos', 'celery', 'cabbage', 'bell pepper', 'onion']
print(sorted(veggies)) # function returns sorted list

['bell pepper', 'cabbage', 'celery', 'onion', 'potatos']


In [ ]:
print(veggies) # function does not modify the original list.

['potatos', 'celery', 'cabbage', 'bell pepper', 'onion']


In [384]:
# by dafault ints and foats will be sorted in ascending order.
# strings sorted alphabetically based on the Unicode code point value of each character
# 'A' -> 65
# 'a' -> 97

In [385]:
sorted(['Bacon', 'bun', 'Apple', 'anger'])

['Apple', 'Bacon', 'anger', 'bun']

In [387]:
def last_letter(text):
    return text[-1]

In [389]:
last_letter('hiro')

'o'

In [390]:
sorted(veggies, key=last_letter)

['cabbage', 'onion', 'bell pepper', 'potatos', 'celery']

In [17]:
# tuplie
# tple are IMMUTABLE

mutable_synonyms = ('changeable', 'fluctuating', 'inconsistent', 'variable')
mutable_synonyms

('changeable', 'fluctuating', 'inconsistent', 'variable')

In [3]:
empty = ()

In [5]:
empty

()

In [7]:
also_empty = tuple ()
also_empty

()

In [9]:
empty.append('hi')

AttributeError: 'tuple' object has no attribute 'append'

In [10]:
len(mutable_synonyms)

4

In [12]:
mutable_synonyms

('changeable', 'fluctuating', 'inconsistent', 'variable')

In [ ]:
sorted(mutable_synonyms)

['changeable', 'fluctuating', 'inconsistent', 'variable']

In [21]:
mutable_synonyms + ('motifiable', 'shifting')

('changeable',
 'fluctuating',
 'inconsistent',
 'variable',
 'motifiable',
 'shifting')

In [22]:
# sets 
#{}
# mutable, unordered and distinct

In [26]:
things = {'coat', 'lock', 'book', 'apple', 'hair', 'box', 'xylophone', 'lock', 'book'}
things

{'apple', 'book', 'box', 'coat', 'hair', 'lock', 'xylophone'}

In [29]:
visitor_post_codes = ['M5R', 'M5V', 'M1M', 'M1M']
visitor_post_codes

['M5R', 'M5V', 'M1M', 'M1M']

In [31]:
set(visitor_post_codes)

{'M1M', 'M5R', 'M5V'}

In [34]:
'hiro' in things

False

In [37]:
things.add('lock')
things

{'apple', 'book', 'box', 'coat', 'hair', 'lock', 'xylophone'}

In [39]:
things.add('mirorr')

In [41]:
things

{'apple', 'book', 'box', 'coat', 'hair', 'lock', 'mirorr', 'xylophone'}

In [50]:
things.remove('box')

KeyError: 'box'

In [51]:
things

{'book', 'coat', 'hair', 'lock', 'mirorr', 'xylophone'}

In [46]:
empty_set = set()

In [52]:
empty_set
# empty_list = []
# empty_tuple = ()

set()

In [60]:
rainbow = {'red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'}
olympic_flag = {'red', 'green', 'yellow', 'blue'}

rainbow.difference(olympic_flag)

{'indigo', 'orange', 'violet'}

In [62]:
olympic_flag.difference(rainbow)

set()

In [63]:
rainbow.symmetric_difference(olympic_flag)

{'indigo', 'orange', 'violet'}

In [66]:
rainbow.intersection(olympic_flag)

{'blue', 'green', 'red', 'yellow'}

In [68]:
rainbow.union(olympic_flag)

{'blue', 'green', 'indigo', 'orange', 'red', 'violet', 'yellow'}

In [ ]:
# dictionary
# {} key:value pairs
# ordered and mutable
# every key in a dictionary is unique, immutable data type
# values can be any data type



In [71]:
capital = {'Canada': 'Ottawa', 
           'United States': 'Washington, D.C.',
           'Mexico': 'Mexico City'}

In [72]:
capital

{'Canada': 'Ottawa',
 'United States': 'Washington, D.C.',
 'Mexico': 'Mexico City'}

In [73]:
olympic_cities = {2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}

In [75]:
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}

In [79]:
all_olympic_hosts = {'summer': olympic_cities,
                     'winter': {2022:'beijing'}}

In [81]:
all_olympic_hosts

{'summer': {2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'},
 'winter': {2022: 'beijing'}}

In [84]:
emplty_dictionary = {}

In [85]:
emplty_dictionary

{}

In [86]:
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}

In [89]:
olympic_cities[2020]

'Tokyo'

In [90]:
all_olympic_hosts

{'summer': {2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'},
 'winter': {2022: 'beijing'}}

In [95]:
all_olympic_hosts['winter']

{2022: 'beijing'}

In [97]:
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}

In [99]:
olympic_cities.get(2004, 'Athens')

'Athens'

In [101]:
olympic_cities.get(2027)

In [103]:
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}

In [105]:
2016 in olympic_cities

True

In [107]:
'Rio de Janiero' in olympic_cities

False

In [109]:
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}

In [111]:
olympic_cities[2008] = 'Barcelona'

In [113]:
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London', 2008: 'Barcelona'}

In [114]:
olympic_cities[2008] = 'Beijing'

In [116]:
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London', 2008: 'Beijing'}

In [118]:
all_olympic_hosts

{'summer': {2020: 'Tokyo',
  2016: 'Rio de Janiero',
  2012: 'London',
  2008: 'Beijing'},
 'winter': {2022: 'beijing'}}

In [120]:
del olympic_cities[2020]

KeyError: 2020

In [122]:
olympic_cities

{2016: 'Rio de Janiero', 2012: 'London', 2008: 'Beijing'}

In [123]:
all_olympic_hosts.keys()

dict_keys(['summer', 'winter'])

In [125]:
olympic_cities.values()

dict_values(['Rio de Janiero', 'London', 'Beijing'])

In [127]:
olympic_cities.items()

dict_items([(2016, 'Rio de Janiero'), (2012, 'London'), (2008, 'Beijing')])

In [128]:
# for loop will run an indented block of code for every item in an iterable 
# iterable -> data type list, tuple, set, dictionary and string. 

In [131]:
vowels = ['a', 'e', 'i', 'o', 'u']

In [133]:
vowels

['a', 'e', 'i', 'o', 'u']

In [136]:
for i in vowels:
    print(i)

a
e
i
o
u


In [139]:
for i in range(7): # range() creates an iterable to loop over
    print(i, i*2) # i=1

0 0
1 2
2 4
3 6
4 8
5 10
6 12


In [143]:
input_files = ['data_01.csv', 'data_02.csv', 'data_03.csv']
output_file = []

for i in input_files:
    output_file_name = 'processed_' + i.replace('.csv', '.xlsx')
    # output_file_name = 'processed_data.01.xlsx
    output_file.append(output_file_name)
    print(output_file)


['processed_data_01.xlsx']
['processed_data_01.xlsx', 'processed_data_02.xlsx']
['processed_data_01.xlsx', 'processed_data_02.xlsx', 'processed_data_03.xlsx']


In [145]:
stops = ['Sheppard-Younge', 'Bayview', 'Leslie', 'Bessarion', 'Don Mills']

In [147]:
for idx, stop in enumerate(stops):
    print(idx, stop)

0 Sheppard-Younge
1 Bayview
2 Leslie
3 Bessarion
4 Don Mills


In [150]:
numbers = [1, 10, 100, 10000]

for idx, val in enumerate(numbers):
    numbers[idx] = val * 2

numbers

[2, 20, 200, 20000]

In [155]:
lats = (45.32, 49.11, 11.11)
lons = (23.45, 67.78, 90.21)

for i, j in zip(lats, lons):
    print(i, j)

45.32 23.45
49.11 67.78
11.11 90.21


In [161]:
for fruit in ['apple', 'banana', 'pear']:
    for veg in ['potato', 'celery', 'onion']:
        print(fruit, veg)

apple potato
apple celery
apple onion
banana potato
banana celery
banana onion
pear potato
pear celery
pear onion


In [163]:
countdown = 4
while countdown >0:
    print(countdown)
    countdown-= 1

4
3
2
1


In [ ]:
countdown = 4

while countdown > 0:
    print(countdown)
    if countdown == 3:
        print('We are breaking the loop early.')
        break
    countdown -= 1

print('Done interating.')

4
3
We are breaking the loop early.
Done interating.


4
3
We are breaking the loop early.
Done interating.


In [ ]:
while True:
    password = input("what's the password?")

    if password.lower() == 'open seseme':
        print('you are in!')
        break

In [170]:
wishes = 3

while wishes > 0
wish = input('make a wish: ')
    if 'infinite wishes' in wish.lower():
        print('you can\'t do that!')
        continue
    else:
        print('wish granted.')
    wishes -= 1
print('you have used all your wishes')

SyntaxError: invalid syntax (1993718752.py, line 3)

In [193]:
# build-in function open()
# string for file path or location of the file to opne
# one-character string to indicate if we open the file in:
#'r' -> read mode
#'w' -> write mode
#'a' -> append mode

with open('/Users/Hiro/python/05_src/data/slides_data/california_housing_test.csv', 'r') as f:

IndentationError: expected an indented block (1623272342.py, line 8)

In [195]:
provinces = ['BC', 'AB', 'SK', 'MB', 'ON', 'QC', 'NL', 'NB', 'NS', 'PE']
with open('/Users/Hiro/python/02_activities/provices.txt', 'w') as province_file: 
    province_file.writelines(provinces)

In [197]:
import os

In [199]:
os.getcwd()

'/Users/Hiro/python/01_materials'

In [201]:
os.listdir()

['Untitled-1.ipynb', 'slides']

In [204]:
cwd = os.getcwd()
full_path = []

for i in os.listdir():
    temp = os.path.join(cwd, i)
    full_path.append(temp)    


In [206]:
full_path

['/Users/Hiro/python/01_materials/Untitled-1.ipynb',
 '/Users/Hiro/python/01_materials/slides']

In [211]:
text = 'Lavender is a small purple flower.'

if os.path.exists('plants.txt'):
    print('prints.txt already exists')
else:
    with open('plants.txt', 'w') as f:
        f.write(text)

prints.txt already exists


In [212]:
# class: this is a blueprint or template for creating objects, 
# define the attributes and methods that objects fo that class will have. 

# object: specific instance of a class, which have attributes and behaviors.

# methods: funtions associaed with a class anc can be called on objects of 
# that class to perform certain actions or operations

# attributes: piece of data that belongs to an object, represent the state of the object.



In [213]:
car1_name = 'Car 1'
car1_brand = 'Honda'
car1_model = 'Civic'
car1_vin = 'MSIEKAIJNI'

car2_name = 'Car 2'
car2_brand = 'VW'
car2_model = 'Golf'
car2_vin = 'KMLKKLJKLN'

In [ ]:
class Car: 
    def __init__(self, name, brand, model, vin):
        #__init__ automatically called when a new object of a class is created.
        # initialize the ojbect's attributes or properties.

        # self is a reference to the current instatnce of the class.
        # first parameter in every method definition inside a class.
        self.name = name
        self.brand = brand
        self.model = model
        self.vin = vin

    def honk(self):
        print("beep beep")

In [217]:
hiro_car = Car('Car1', 'Honda', 'Civic', 'MSIEKAIJNI')

In [220]:
hiro_car.name

'Car1'

In [222]:
hiro_car.brand

'Honda'

In [228]:
hiro_car.vin

'MSIEKAIJNI'

In [235]:
hiro_car.nonk()

beep beep


In [237]:
import numpy as np

In [244]:
a = np.array([[1, 2, 3],
             [3, 2, 1]])

In [246]:
print(a.ndim)

2


In [248]:
print(a.shape)

(2, 3)


In [250]:
print(a.size)

6


In [252]:
print(a.dtype)

int64


In [259]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [260]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [264]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [265]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [269]:
np.arange(1, 5, 1)

array([1, 2, 3, 4])

In [270]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [278]:
np.random.seed(1)
np.random.randint(1, 10, (3, 4))

array([[6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3]])

In [280]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [282]:
onedim_arr = np.array([1, 2, 3, 4, 5])
multidim_arr = np.repeat(onedim_arr, 5)
multidim_arr

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

In [284]:
multidim_arr = np.tile(onedim_arr, (5, 1))
multidim_arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [285]:
multidim_arr = np.tile(onedim_arr, (3, 3))
multidim_arr

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [286]:
b = np.array([[5, 4, 3, 2, 1, 0],
              [10, 8, 6, 4, 2, 0]])

b

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [288]:
b.T

array([[ 5, 10],
       [ 4,  8],
       [ 3,  6],
       [ 2,  4],
       [ 1,  2],
       [ 0,  0]])

In [290]:
b.reshape(4, 3)

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [292]:
b.flatten()

array([ 5,  4,  3,  2,  1,  0, 10,  8,  6,  4,  2,  0])

In [294]:
np.hstack((b, a))

array([[ 5,  4,  3,  2,  1,  0,  1,  2,  3],
       [10,  8,  6,  4,  2,  0,  3,  2,  1]])

In [295]:
np.vstack((b.reshape(4,3), a))

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0],
       [ 1,  2,  3],
       [ 3,  2,  1]])

In [297]:
arr1 = np.array([5, 10, 15, 20])
arr1

array([ 5, 10, 15, 20])

In [299]:
arr2 = np.arange(5, 9)

In [ ]:
arr1 - arr2


array([ 0,  4,  8, 12])

In [302]:
arr1*2

array([10, 20, 30, 40])

In [304]:
arr2 + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [306]:
arr1.max()

20

In [307]:
arr1.sum()

50

In [309]:
arr1.mean()

12.5

In [310]:
np.median(arr1)

12.5

In [315]:
tens = np.arange(0, 120, 10).reshape(3, 4)
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [320]:
horizontal = np.array([-5, -10, -15, -20])
horizontal

array([ -5, -10, -15, -20])

In [324]:
vertical = np.array([[100],
                     [200],
                     [300]])

vertical

array([[100],
       [200],
       [300]])

In [325]:
tens + horizontal + vertical

array([[ 95, 100, 105, 110],
       [235, 240, 245, 250],
       [375, 380, 385, 390]])

In [326]:
# axis = 0: colum-wise operation (down the rows)
# axis = 1: row-wise operation (across the columns)

In [327]:
tens.mean(axis=0)

array([40., 50., 60., 70.])

In [329]:
tens.mean(axis=1)

array([15., 55., 95.])

In [331]:
arr1

array([ 5, 10, 15, 20])

In [333]:
arr1[1]

10

In [335]:
arr1[1:3]

array([10, 15])

In [337]:
tens[1, 2]

60

In [339]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [342]:
tens[0]

array([ 0, 10, 20, 30])

In [346]:
tens[:,0]

array([ 0, 40, 80])

In [350]:
matrix1 = np.array([1, 4, 12])

In [352]:
matrix2 = matrix1

In [ ]:
matrix2



array([ 1,  4, 12])

In [357]:
matrix3 = matrix1.copy()
matrix3

array([ 1,  4, 12])

In [359]:
matrix1[0] = 1000

In [361]:
matrix2

array([1000,    4,   12])

In [362]:
matrix3

array([ 1,  4, 12])